language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "6.0"
  - "6.9"
  - "8.0"
  - "8.9"
services: mongodb
env:
  - NODE_ENV=test
before_install:
  - "npm install multer@^1.0.0"
before_script:
  - sleep 15
after_script:
  - npm run coveralls
