language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"
  - "5.1"
  - "5.2"
  - "5.3"
  - "5.4"
services: mongodb
env:
  - NODE_ENV=test
before_script:
  - sleep 15
after_script:
  - npm run-script coveralls
